### PR TITLE
feature/ubuntu22-04

### PR DESCRIPTION
**Pull request by tsaubergine**
Add Dockerfiles and CircleCI config.

Related: https://github.com/jaiarobotics/jaiabot-rootfs-gen/pull/50

### CODE REVIEW

**Comment by ealvar3z** [comment]
It's still failing because although this commit 8423d2e3b1adefb38947ab165baffb7c30a7fbab updated the property type, the `Props`interface in `RCControllerPanel.tsx` still needs to be updated to:

```typescript
clearInterval: (timer: NodeJS.Timeout) => void
```
P.S: I am w/ MCWL, we evaluated and observed the Jaiabot during TOEE

**Comment by tsaubergine** [comment]
> It's still failing because although this commit [8423d2e](https://github.com/jaiarobotics/jaiabot/commit/8423d2e3b1adefb38947ab165baffb7c30a7fbab) updated the property type, the `Props`interface in `RCControllerPanel.tsx` still needs to be updated to:
> 
> ```ts
> clearInterval: (timer: NodeJS.Timeout) => void
> ```
> 
> P.S: I am w/ MCWL, we evaluated and observed the Jaiabot during TOEE

@ealvar3z thanks!
@ferrom-jaia Can you look into this? I'm not up on the JCC code.

**Comment by ferrom-jaia** [comment]
> > It's still failing because although this commit [8423d2e](https://github.com/jaiarobotics/jaiabot/commit/8423d2e3b1adefb38947ab165baffb7c30a7fbab) updated the property type, the `Props`interface in `RCControllerPanel.tsx` still needs to be updated to:
> > ```ts
> > clearInterval: (timer: NodeJS.Timeout) => void
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > P.S: I am w/ MCWL, we evaluated and observed the Jaiabot during TOEE
> 
> @ealvar3z thanks! @ferrom-jaia Can you look into this? I'm not up on the JCC code.

Yes, I will look into this!

**Comment by tsaubergine** [comment]
@ferrom-jaia What's holding this up?

**Review by ferrom-jaia — APPROVED** [review]
Looks good! Tested by Jeff.

**Pull request merged**
