### PR TITLE
feature/jdv-select-logs-shows-hub-storage-space-left

### PR DESCRIPTION
**Pull request by edsanville**

### CODE REVIEW

**Review by ferrom-jaia — CHANGES_REQUESTED** [review]
Tested in sim. The logs no longer showed for me in the select log panel.

**Review by ferrom-jaia — CHANGES_REQUESTED** [review]
Tested in sim and worked great! Can we add function comments for the ones that were created/modified: 

https://github.com/jaiarobotics/jaiabot/blob/1.y/src/doc/markdown/page_110_coding_standards.md

**Comment by edsanville** [comment]
> Tested in sim and worked great! Can we add function comments for the ones that were created/modified:
> 
> https://github.com/jaiarobotics/jaiabot/blob/1.y/src/doc/markdown/page_110_coding_standards.md

Sure thing!

**Review by ferrom-jaia — APPROVED** [review]
Looks great! Tested on my machine.

**Pull request merged**
