### PR TITLE
bug/ip-incorrect-for-jdv-liaison-when-using-vpn-jaia-532

### PR DESCRIPTION
**Pull request by edsanville**
The client JS checks the location's hostname and matches it against "hXfX" or "172.23.X.X,"  and if either one matches then it assumes you're on the VPN and uses the "172.23" IP prefix in that case.

### CODE REVIEW

**Comment by michael-jaia** [comment]
Will we need to update this for use with the cloudhub? I have not used the web apps running in the cloud, but I believe they use IPv6. I'm also thinking this function might be more suited for a utility file so we do not cloud UI code with logic to resolve IP addresses.

**Comment by edsanville** [comment]
> Will we need to update this for use with the cloudhub? I have not used the web apps running in the cloud, but I believe they use IPv6. I'm also thinking this function might be more suited for a utility file so we do not cloud UI code with logic to resolve IP addresses.

Good point for both.  I haven't used CloudHub and know nearly nothing about it.  Perhaps it's time to get that short introduction to that way of doing things, and I can come back and add IPv6 support.

In the meantime, I'll move this function off to a utility file.

**Review by ferrom-jaia — APPROVED** [review]
Looks good. I am going to add the task for the cloud hub links.

**Comment by tsaubergine** [comment]
> Looks good. I am going to add the task for the cloud hub links.

Did this task ever get created? I still get a bad link (10.23.xxx.yyy) when clicking through to JDV from JCC in VirtualHub/CloudHub

**Comment by ferrom-jaia** [comment]
I checked the backlog and I did not find it. I added the issue: https://jaia-innovation.atlassian.net/jira/software/c/projects/JAIA/boards/15/backlog?selectedIssue=JAIA-1835

**Pull request merged**
