### PR TITLE
Update jaiabot-software diagram to reflect current implementation

### PR DESCRIPTION
**Pull request by tsaubergine**

### CODE REVIEW

**Review by ferrom-jaia — COMMENTED** [review]
Jaia Data Vision and Jaia Command & Control (vs JaiaBot ...).

I am not sure about the jaiabot_topside_manager. I do not think this is used.

**Review by ferrom-jaia — CHANGES_REQUESTED** [review]
Jaia Data Vision and Jaia Command & Control (vs JaiaBot ...).

I am not sure about the jaiabot_topside_manager. I do not think this is used.

**Comment by tsaubergine** [comment]
> Jaia Data Vision and Jaia Command & Control (vs JaiaBot ...).
> 
> I am not sure about the jaiabot_topside_manager. I do not think this is used.

Fixed

**Review by ferrom-jaia — APPROVED** [review]
Looks great!

**Pull request merged**
