### PR TITLE
Ivp helm health

### PR DESCRIPTION
**Pull request by ferrom-jaia**
Added helm health checks for state of the helm (always want DRIVE), desired vars are posting to the moos db, and that nav data is  being posted  to the moos db

If helm is not in DRIVE - error: ERROR__MOOS__HELMIVP_STATE_NOT_DRIVE
If there is no desired vars - error: ERROR__MOOS__HELMIVP_NO_DESIRED_DATA
If there is no data vars (NAV_X) - error: ERROR__MOOS__NO_DATA

[Demo-showing-test-errors](https://user-images.githubusercontent.com/109534520/181299042-a2e6f5e2-1c3c-40be-a99e-beaf61e9892c.mp4
)

[Demo](https://user-images.githubusercontent.com/109534520/181249207-8f422f22-cf8d-473a-884b-9f1313af0d75.mp4)

### CODE REVIEW

**Comment by jason-jaia** [comment]
Is there a way to test/show that it reports FAILED when it should?

**Comment by ferrom-jaia** [comment]
> Is there a way to test/show that it reports FAILED when it should?

Just add new video

**Comment by jason-jaia** [comment]
I approve with the caveat that I trust the state stays in DRIVE even if we're drifting or otherwise stopped in the state machine on purpose.

**Comment by ferrom-jaia** [comment]
> I approve with the caveat that I trust the state stays in DRIVE even if we're drifting or otherwise stopped in the state machine on purpose.

In the jaiabot_gateway_plugin.cpp on line 43:

    // we don't want the Helm in Park ever
    moos().comms().Notify("MOOS_MANUAL_OVERRIDE", "false");

**Comment by jason-jaia** [comment]
OK, then!
________________________________

**Review by tsaubergine — APPROVED** [review]
Looks great, thanks for the videos.

**Pull request merged**
