### PR TITLE
feature/entering-rc-mode-in-failed-state

### PR DESCRIPTION
**Pull request by ferrom-jaia**
Added an override event to allow the operator to enter rc mode when in a failed state. This hopefully helps the operator safely drive their bot back to a safety position. 
Video:
https://jaia-innovation.atlassian.net/wiki/spaces/PD/pages/1089798145/RC+Mode+Entering+in+failed+state

### CODE REVIEW

**Comment by jason-jaia** [comment]
Can we add a popup if your failed state is for critically low battery that RC mode could jeopardize your recovery (less time to float and broadcast your GPS location for emergency retrieval).  Although, you might be 5 feet from the dock and RC on critically low battery would be super useful.

**Comment by ferrom-jaia** [comment]
> jeopardize your recovery

Updated with the alert!

**Comment by jason-jaia** [comment]
Can you post a quick video rather than me getting my simulator to run again?

**Review by jason-jaia — APPROVED** [review]
Approved based on video evidence of the simulator working like a dream.

**Pull request merged**
