### PR TITLE
Added diagram showing the JCC render flowchart

### PR DESCRIPTION
**Pull request by edsanville**
Added render chart in PDF format.

### CODE REVIEW

**Comment by edsanville** [comment]
Please let me know if we want it in another format.

**Comment by edsanville** [comment]
Please let me know if we want it in another format.

**Comment by edsanville** [comment]
Please let me know if we want it in another format.

**Comment by ferrom-jaia** [comment]
For this pull request: can we put the doc in: jaiabot/src/doc/figures, can we also use draw.io to create this diagram to match the other diagrams we have?

**Review by ferrom-jaia — APPROVED** [review]
Looks good!

**Pull request merged**
