### PR TITLE
Implement fusion errors/warnings about missing data streams. 

### PR DESCRIPTION
**Pull request by tsaubergine**
Implemented the following errors/warnings in fusion (all timeout after data_timeout_seconds of no receipt):

- `ERROR__MISSING_DATA__GPS_FIX`: Ok if TPV mode = 2 or 2
- `ERROR__MISSING_DATA__GPS_POSITION`: Ok if receiving lat/lon
- `ERROR__MISSING_DATA__PRESSURE`: Ok if receiving pressure
- `ERROR__MISSING_DATA__HEADING`: Ok if receiving heading
- `ERROR__MISSING_DATA__SPEED`: Ok if receiving speed
- `ERROR__MISSING_DATA__COURSE`: Ok if receiving course over ground / track
- `WARNING__MISSING_DATA__TEMPERATURE`: Ok if receiving (water) temperature
- `WARNING__MISSING_DATA__PITCH`: Ok if receiving Pitch
- `WARNING__MISSING_DATA__ROLL`: Ok if receiving Roll

Added initial value to simulator for lat/lon so we don't fail out on missing data (this position is otherwise meaningless as the sim vehicle will teleport as before when receiving the initial mission/datum update).

Style change `dive_*_debug` -> `dive_*_debug_`.

### CODE REVIEW

**Comment by tsaubergine** [comment]
[S6 - feature/Health-Check-CGPS [0.5]](https://trello.com/c/9D3plpTY/498-s6-feature-health-check-cgps-05)

**Comment by ferrom-jaia** [comment]
Looks good! I think we should have GPS missing as a warning for now.

**Comment by tsaubergine** [comment]
Leaving GPS missing as an error which can be overridden by indoor mode in https://github.com/jaiarobotics/jaiabot/pull/187

**Review by ferrom-jaia — APPROVED** [review]
Tested in simulation

**Pull request merged**
