### PR TITLE
Task/status repo and version

### PR DESCRIPTION
**Pull request by tsaubergine**
Implements https://jaia-innovation.atlassian.net/browse/JAIA-194?atlOrigin=eyJpIjoiOTFhNmYxN2Q4YjE2NDUwYzhjN2UwMTg1ZTAwMTgyYWUiLCJwIjoiaiJ9

I also fixed a bug in jaiabot-debian while testing this PR: https://github.com/jaiarobotics/jaiabot-debian/pull/62

Details:
- Adds deb repository (e.g. "continuous") and release branch (e.g. "1.y") to output of `jaia version` by reading `apt-cache policy jaiabot-embedded`. This will also add it to jaiabot_metadata as these share the same function
- Also add MOOS-IvP version to output of `jaia version` by reading `apt-cache policy moos-ivp-apps`
- Changed 75-jaiabot-status to use the output `jaia version` instead of reading files in `/etc/jaiabot` directly.
- Fix bug where deb packaged version was reporting git hash

New end section of `75-jaiabot-status` when installed using `jaiabot-embedded` deb package:
```
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                       _  _   __ ___  _        __ 
                 \  / |_ |_) (_   |  / \ |\ | (_  
                  \/  |_ | \ __) _|_ \_/ | \| __) 

jaiabot:
  1.10.0~beta2+71+g96e296c2
  deb repository: test
  deb release branch: X.y
goby: 3.1.4
moos: 10.4.0
ivp: 19.8.1+svn9395-10~ubuntu22.04.1
raspberry pi firmware: 
jaiabot rootfs image: 1.0.0~alpha1+87+gfe48629

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

or via git based build:

```
jaiabot:
  1.10.0+0+g96e296c2
  git hash: 96e296c2598fb21064a6ef4a82f156d51faf5924
  git branch: task/status-repo-and-version
goby: 3.1.4
moos: 10.4.0
ivp: 19.8.1+svn9395-10~ubuntu22.04.1
raspberry pi firmware: 1.20220331
jaiabot rootfs image: 1.0.0~alpha1+130+gea8f449
```

### CODE REVIEW

**Comment by edsanville** [comment]
Edge case if the tool can't find jaiabot-status:
```ed@venus:~/projects/jaia/jaiabot$ jaia status
ERROR executing:
	"jaiabot-status" "--binary=jaia status" 
Ensure that Segmentation fault (core dumped)
```

**Review by edsanville — DISMISSED** [review]
Tested and works as advertised

**Comment by tsaubergine** [comment]
> Edge case if the tool can't find jaiabot-status:
> 
> ```
> ERROR executing:
> 	"jaiabot-status" "--binary=jaia status" 
> Ensure that Segmentation fault (core dumped)
> ```

Oops. Thanks for catching this!

Fixed at https://github.com/GobySoft/goby3/pull/321/files, which will be part of Goby 3.1.6 whenever that happens.

With that fix you get a more sensible: 

```
ERROR executing:
	"jaiabot-status" "--binary=jaia status" 
Ensure that jaiabot-status is on your path and is executable.
Application:: uncaught exception: Action was expected to be handled by external tool
terminate called after throwing an instance of 'goby::Exception'
  what():  Action was expected to be handled by external tool
```

**Review by ferrom-jaia — APPROVED** [review]
Looks great! Tested on flat bot.

**Pull request merged**
