### PR TITLE
bug/nproc-in-build-script

### PR DESCRIPTION
**Pull request by edsanville**
Add some documentation to README.md about the environment variables that control the build process.

### CODE REVIEW

**Comment by tsaubergine** [comment]
I like it!

**Review by tsaubergine — DISMISSED** [review]

**Comment by tsaubergine** [comment]
I wonder if it makes more sense to use MemAvailable rather than MemTotal? (Sometimes I have some VMs running that uses a lot of memory)

**Comment by edsanville** [comment]
> I wonder if it makes more sense to use MemAvailable rather than MemTotal? (Sometimes I have some VMs running that uses a lot of memory)

Good point!

**Review by ferrom-jaia — APPROVED** [review]
Looks good! Tested on my machine.

**Pull request merged**
