### PR TITLE
bug/jed-writing-to-bounds-file

### PR DESCRIPTION
**Pull request by edsanville**
This is how it currently works

* JED sends a Bounds message to jaiabot_web_portal in the EngineeringCommand
* jaiabot_engineering sees the Bounds message, loads /etc/jaiabot/bounds.pb.cfg (if it exists and is a text protobuf Bounds message)
* jaiabot_engineering merges the new Bounds message with the one from /etc/jaiabot/bounds.pb.cfg, and re-writes the merged message to /etc/jaiabot/bounds.pb.cfg
* jaiabot_arduino subscribes to the EngineeringCommand message, and also merges the Bounds message with its currently active bounds parameters

### CODE REVIEW

**Comment by michael-jaia** [comment]
Hey Ed, did any of these errors appear in the JED for you while working on this ticket?
jed-error-undef-obj

**Comment by edsanville** [comment]
> Hey Ed, did any of these errors appear in the JED for you while working on this ticket? jed-error-undef-obj

**Comment by edsanville** [comment]
> Hey Ed, did any of these errors appear in the JED for you while working on this ticket? jed-error-undef-obj

Ok, so this comes about because, in the simulator, the Arduino driver isn't running, so it never publishes its bounds to the jaiabot_engineering app.  I can fix the JavaScript so this error message doesn't come up in the console.

**Review by ferrom-jaia — APPROVED** [review]
Looks good! Tested in sim and on a bot and hub.

**Pull request merged**
